name: Run CAMERA Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract and List Files
      run: |
        unzip "CAMERA PLUS LOCATION.zip"
        ls -la
        cd "CAMERA PLUS LOCATION"
        ls -la
